### ISSUE TITLE
探索対象発見

### ISSUE THREAD

**Issue by kazukishirasu** [rdc-autonomous-mobile-robot-project/box2_ToDo#3]
## 探索対象発見

- [x] データ集め
- [x] アノテーション
- [x] 学習・認識
- [ ] 探索対象発見モードに切り替え
- [ ] プランニング
- [ ] 経路復帰

**Comment by nkm071** [comment]
とりあえず編集できるようにgoogleドキュメントのURL
https://docs.google.com/document/d/1eP60BEa-b2C_JY3VNSvlPLSNu-0Q3-E-PHzrZbnfgt8/edit?usp=sharing

**Comment by nkm071** [comment]
レギュレーション変更により，探索対象発見がなくなったのでissueを閉じたい

**Comment by nkm071** [comment]
@kazukishirasu @YukiTakahashi4690 クローズをお願いしてもよろしいでしょうか．
