### ISSUE TITLE
荷物の配送

### ISSUE THREAD

**Issue by kazukishirasu** [rdc-autonomous-mobile-robot-project/box2_ToDo#5]
## Description

1. To
2. Do

- [ ]

**Comment by nkm071** [comment]
# 選択課題のレギュレーション
[レギュレーション](https://tsukubachallenge.jp/2023/regulations/tasks)

## 荷物の配送
- [x] カメラの取り付けパーツの作成
- [x] jetsonにyolov5の環境構築
- [x] yolov5の学習済みモデルの作成
- [ ] 経路計画

**Comment by nkm071** [comment]
https://github.com/rdc-autonomous-mobile-robot-project/box2_ToDo/issues/5#issuecomment-1657196031
jetsonにyolov5の環境構築をする件に関して別のPCにyolov5の環境を構築するため完了とする

**Comment by nkm071** [comment]
https://github.com/rdc-autonomous-mobile-robot-project/box2_ToDo/issues/5#issuecomment-1657196031
また同一issue内に三個のタスクがあるのはやりにくいのでそれぞれにissueを立てる

**Comment by nkm071** [comment]
## 荷物の配送
カメラの取り付けパーツの作成
https://github.com/rdc-autonomous-mobile-robot-project/box2_ToDo/issues/7

yolov5の学習済みモデルの作成
https://github.com/rdc-autonomous-mobile-robot-project/box2_ToDo/issues/8

経路計画
https://github.com/rdc-autonomous-mobile-robot-project/box2_ToDo/issues/9

**Comment by nkm071** [comment]
## 先輩から9/4日に頂いたアドバイス
https://github.com/rdc-autonomous-mobile-robot-project/box2_ToDo/issues/10

**Comment by nkm071** [comment]
荷物の配送に使用するカメラの赤い部分が壊れてしまった．box2に取り付けて画像を取得する場合，ぐらつくことは間違いないと思われる．

![image](https://github.com/rdc-autonomous-mobile-robot-project/box2_ToDo/assets/91714744/e50dd5de-0725-451d-9e5d-34ca9e1b85e1)

**Comment by nkm071** [comment]
![image](https://github.com/rdc-autonomous-mobile-robot-project/box2_ToDo/assets/91714744/8046b738-12d1-4012-b0ba-679805330ebe)
ラベルの貼り付け位置は上面と側面の二か所だけか確認

**Comment by nkm071** [comment]
こちらも使用しないと思いますので閉じます。
